web_server/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :messages

  map.resources :users

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

web_server/app/models/.#user.rb
sarcilav@b18p5con6.eafit.edu.co.260

web_server/app/models/api/message.rb
require 'httparty'

module API
  class Message
    include HTTParty
    base_uri 'http://localhost:8080'

    def self.create(message,owner)
      post("/messages.xml", :body => { "message" => { "msg" => message, "user-id" => owner } })
    end
    
    def self.all
      get("/messages.xml")
    end
    
    def self.find(id)
      get("/messages/#{id}.xml")
    end
    def self.destroy(id)
      delete("/messages/#{id}.xml")
    end
  end
end

web_server/app/models/api/user.rb
require 'httparty'
require 'crack'
module API
  class User
    include HTTParty
    base_uri 'http://localhost:8080'
    
    def self.getAll
      get("/users.xml")
    end
    
    def self.getUser(id)
      get("/users/#{id}.xml")
    end
    
    def self.login(username)
      post("/users.xml", :body => { "user" => { "name" => username } })
    end
    
    def self.logout(id)
      delete("/users/#{id}.xml")
    end
  end
end

web_server/app/models/message.rb
class Message
  attr_accessor :msg, :owner
  def initialize(attr = {})
    @msg = attr["msg"]
    @owner = attr["user_id"]
    @id = attr["id"]
  end

  def self.find(id)
    single(API::Message.find(id))
  end
  def destroy
    API::Message.destroy(@id)
  end
  def self.create(message, owner)
    single(API::Message.create(message, owner))
  end
  
  def self.all
    multiple(API::Message.all())
  end
  protected
  def self.single(answer)
    status = answer.response.code.to_i
    if status >= 200 and status < 300
      return Message.new(answer.parsed_response["message"])
    else
      raise Exception.new("Problem to load single message instance, message #{answer.response.code} #{answer.response.code_type}")
    end
  end
  def self.multiple(answer)
    status = answer.response.code.to_i
    if status >= 200 and status < 300
      ans = []
      array = answer.parsed_response["messages"]
      array.each do |x|
        ans << Message.new(x)
      end
      return ans
    else
      raise Exception.new("Problem to load multiple messages instances, message #{answer.response.code} #{answer.response.code_type}")
    end    
  end
end

web_server/app/models/user.rb
class User
  attr_accessor :name, :id
  def initialize(attr = {})
    @name = attr["name"]
    @id = attr["id"].to_s
  end

  def self.create(name)
    single(API::User.login(name))
  end
  
  def self.all
    multiple(API::User.getAll())
  end
  
  def self.find(id)
    single(API::User.getUser(id))
  end
  
  def destroy
    API::User.logout(@id)
  end
  protected
  def self.single(answer)
    status = answer.response.code.to_i
    if status >= 200 and status < 300
      return User.new(answer.parsed_response["user"])
    else
      raise Exception.new("Problem to load single user instance, message #{answer.response.code} #{answer.response.code_type}")
    end
  end
  def self.multiple(answer)
    status = answer.response.code.to_i
    if status >= 200 and status < 300
      ans = []
      array = answer.parsed_response["users"]
      array.each do |x|
        ans << User.new(x)
      end
      return ans
    else
      raise Exception.new("Problem to load multiple useres instances, message #{answer.response.code} #{answer.response.code_type}")
    end    
  end
end

web_server/app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

web_server/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end
  
  def show
    @message = Message.find(params[:id])
  end
  
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.create(params[:message])
  end
  
  def edit
    @message = Message.find(params[:id])
  end
  
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    flash[:notice] = "Successfully destroyed message."
    redirect_to messages_url
  end
end

web_server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(params[:user][:name])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.create(params[:user][:name])
    redirect_to user_path(@user)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully destroyed user."
    redirect_to users_url
  end
end

web_server/app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

web_server/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

web_server/app/helpers/messages_helper.rb
module MessagesHelper
end

web_server/app/helpers/users_helper.rb
module UsersHelper
end

web_server/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
	<!--<meta http-equiv="refresh" content="5" >-->
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>
  </body>
</html>

web_server/app/views/messages/_form.html.erb
<% form_for @message do |f| %>
  <p>
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </p>
  <p>
    <%= f.label :msg %><br />
    <%= f.text_area :msg %>
  </p>
  <p><%= f.submit %></p>
<% end %>

web_server/app/views/messages/edit.html.erb
<% title "Edit Message" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", message_path(@message.id) %> |
  <%= link_to "View All", messages_path %>
</p>

web_server/app/views/messages/index.html.erb
<% title "Messages" %>

<table>
  <tr>
    <th>Owner</th>
    <th>Msg</th>
  </tr>
  <% for message in @messages %>
    <tr>
      <td><%=h message.owner %></td>
      <td><%=h message.msg %></td>
      <td><%= link_to "Show", message_path(message.id) %></td>
      <td><%= link_to "Destroy", message_path(message.id), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Message", new_message_path %></p>

web_server/app/views/messages/new.html.erb
<% title "New Message" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", messages_path %></p>

web_server/app/views/messages/show.html.erb
<% title "Message" %>

<p>
  <strong>Owner:</strong>
  <%=h @message.owner %>
</p>
<p>
  <strong>Msg:</strong>
  <%=h @message.msg %>
</p>

<p>
  <%= link_to "Destroy", messages_path(@message.id), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", messages_path %>
</p>

web_server/app/views/users/_form.html.erb
<% form_for @user do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

web_server/app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", user_path(@user.id) %> |
  <%= link_to "View All", users_path %>
</p>

web_server/app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%=h user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
      <td><%= link_to "Edit", edit_user_path(user.id) %></td>
      <td><%= link_to "Destroy", user_path(user.id), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

web_server/app/views/users/new.html.erb
<% title "New User" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", users_path %></p>

web_server/app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%=h @user.name %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user.id) %> |
  <%= link_to "Destroy", user_path(@user.id), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>